# Generated by Django 5.0 on 2023-12-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeModel',
            fields=[
                ('Roll', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('Bank_balance', models.BigIntegerField()),
                ('Agree_the_term', models.BooleanField()),
                ('Date_of_birth', models.DateField()),
                ('Max_holding_breath', models.DurationField()),
            ],
        ),
    ]
