# Generated by Django 5.0 on 2024-01-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musician', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musiciandb',
            old_name='Album_Name',
            new_name='First_Name',
        ),
        migrations.RemoveField(
            model_name='musiciandb',
            name='Rating',
        ),
        migrations.RemoveField(
            model_name='musiciandb',
            name='Release_date',
        ),
        migrations.RemoveField(
            model_name='musiciandb',
            name='album',
        ),
        migrations.AddField(
            model_name='musiciandb',
            name='Email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musiciandb',
            name='Instrument_type',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musiciandb',
            name='Last_Name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musiciandb',
            name='Phone_number',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
    ]
