# Generated by Django 5.0 on 2024-01-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=40)),
                ('Last_Name', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_number', models.CharField(max_length=14)),
                ('Instrument_type', models.CharField(max_length=14)),
            ],
        ),
    ]
