# Generated by Django 5.0 on 2024-01-01 09:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Album', '0001_initial'),
        ('Musician', '0002_rename_album_name_musiciandb_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumdb',
            old_name='First_Name',
            new_name='Album_Name',
        ),
        migrations.RemoveField(
            model_name='albumdb',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='albumdb',
            name='Instrument_type',
        ),
        migrations.RemoveField(
            model_name='albumdb',
            name='Last_Name',
        ),
        migrations.RemoveField(
            model_name='albumdb',
            name='Phone_number',
        ),
        migrations.AddField(
            model_name='albumdb',
            name='Rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='albumdb',
            name='Release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='albumdb',
            name='musician',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Musician.musiciandb'),
            preserve_default=False,
        ),
    ]
